### ISSUE TITLE
Crash caused when deleting a skin

### ISSUE THREAD

**Issue by SSBSenpai** [Mowjoh/Meteor-Skin-Library#3]
![ss 2016-11-01 at 04 45 18](https://cloud.githubusercontent.com/assets/23186889/19884276/610c2f32-9fef-11e6-8bab-ce5192d749a9.png)

This happened when deleting the 9th skin. The three skins after it had metadata and were downloaded directly via a Meteor download link on Gamebanana. I don't believe skin 9 had any metadata.

After the error was cleared and skins 10-12 (now 9-11) were reinstalled, I tested moving them around and the metadata moved with them. Perhaps a result of swapping a skin with metadata to a slot with one without?

**Comment by Mowjoh** [comment]
I'm now treating this subject !

**Comment by Mowjoh** [comment]
The problem is fixed
