### ISSUE TITLE
Custom nameplate for Moved DLC characters aren't added correctly.

### ISSUE THREAD

**Issue by Garro** [Mowjoh/Meteor-Skin-Library#5]
It seems that with moved DLC character (AKA, characters that have been set to DLC = 0), custom name aren't set correctly within character_db.bin file, so whenever one imports their Meteor Library to SE the assigned nameplate gets wiped back to 0.

I have only tested this with Lucas.

**Comment by Mowjoh** [comment]
nameplate functionality isn't included in your version of MSL. it can't work like you expect it to atm
