### ISSUE TITLE
Single nameplate for multiples costumes.

### ISSUE THREAD

**Issue by Garro** [Mowjoh/Meteor-Skin-Library#6]
This is more like an oversight or requesting a feature than a bug.

I noticed that for custom nameplates, you can't make a single nameplate works with more than the assigned costume. For example, I have two Linkle costumes in the 09 and 10 slots, but I'm using a single chrn_11_Link_09 file for both of them. There's no way to tell Meteor that I'm using the same nameplate for both of them so exporting the skins to SE would leave the second Linkle back to the default nameplate.

Re-adding the same nameplate again for the second costume helps overcoming this issue, but that would make Smash mod folder untidy in the long run, not to mention it would be a pain to manually add each entry in the melee file if you're using 8 costumes with the same nameplate.

**Comment by Mowjoh** [comment]
Hi ! 
I know very well about this request.
I've been working on a major update, and that update will fix alot of issues,
including this. I'm gonna switch the logic of the app to another, allowing for specific nameplate functionality (doing the edits for you)
Also, allowing to add a nameplate and use it for several skins.

So, I'm glad to tell, you that I thought of it, and am developing it
